In [ ]:
!pip install pandas

2
100 200
200 100
200.0

In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('rtsd-public/classification/rtsd-r3/gt_train.csv', sep=',')

In [4]:
df1 = pd.read_csv('rtsd-public/classification/rtsd-r3/numbers_to_classes.csv', sep=',')

In [16]:
df

         filename  class_number sign_class
0      000000.png            24        2.1
1      000001.png            24        2.1
2      000002.png            24        2.1
3      000003.png            24        2.1
4      000004.png            18       1.23
...           ...           ...        ...
70682  070682.png            18       1.23
70683  070683.png            18       1.23
70684  070684.png            18       1.23
70685  070685.png            18       1.23
70686  070686.png            18       1.23

[70687 rows x 3 columns]

In [6]:
df1.head()

   class_number sign_class
0             0        1_1
1             1       1_11
2             2     1_11_1
3             3       1_12
4             4     1_12_2

In [11]:
df.insert(2, 'sign_class', value, allow_duplicates = False)

In [2]:
import pandas as pd

In [7]:
ist = df1['sign_class'].tolist()
ist = [i.replace('_', '.') for i in ist]

In [8]:
jst = df['class_number'].tolist()
jst

[24,
 24,
 24,
 24,
 18,
 24,
 18,
 18,
 18,
 9,
 18,
 9,
 18,
 44,
 9,
 18,
 44,
 9,
 18,
 80,
 80,
 42,
 80,
 42,
 80,
 42,
 80,
 79,
 77,
 79,
 79,
 77,
 79,
 79,
 79,
 79,
 79,
 79,
 77,
 77,
 77,
 80,
 77,
 80,
 80,
 80,
 80,
 80,
 80,
 79,
 79,
 79,
 79,
 77,
 79,
 77,
 79,
 79,
 77,
 79,
 79,
 77,
 79,
 79,
 77,
 79,
 77,
 79,
 77,
 77,
 77,
 77,
 77,
 77,
 77,
 77,
 77,
 24,
 24,
 25,
 25,
 79,
 79,
 79,
 79,
 25,
 25,
 25,
 25,
 79,
 25,
 79,
 79,
 79,
 79,
 65,
 65,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 79,
 24,
 79,
 79,
 24,
 79,
 24,
 77,
 77,
 79,
 79,
 79,
 79,
 79,
 79,
 77,
 77,
 77,
 15,
 19,
 15,
 19,
 77,
 79,
 79,
 77,
 79,
 79,
 79,
 79,
 79,
 79,
 77,
 24,
 77,
 24,
 56,
 77,
 24,
 77,
 24,
 56,
 77,
 24,
 56,
 24,
 56,
 24,
 56,
 24,
 56,
 24,
 56,
 56,
 55,
 79,
 55,
 79,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 64,
 67,
 57,
 21,
 67,
 75,
 24,
 75,
 24,
 24,
 57,
 24,
 24,
 24,
 24,
 24,
 24,
 50,
 67,
 50,
 67,
 50,
 7,
 7,
 7,
 67,
 67,
 25,
 59,
 25,
 59,
 77,
 50,
 50,
 93,
 93,
 93,
 24,
 24,
 24,
 55,
 50,
 55,
 50,
 67,
 50,
 65,
 65,
 59,
 59,
 75,
 59,
 75,
 75,
 96,
 96,
 96,
 77,
 77,
 77,
 77,
 77,
 77,
 77,
 77,
 74,
 77,
 74,
 77,
 77,
 74,
 74,
 74,
 74,
 101,
 101,
 101,
 101,
 101,
 101,
 101,
 101,
 101,
 67,
 67,
 67,
 67,
 67,
 67,
 67,
 67,
 67,
 79,
 79,
 50,
 50,
 50,
 79,
 50,
 79,
 50,
 79,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 75,
 75,
 75,
 75,
 75,
 11,
 75,
 11,
 75,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 50,
 50,
 50,
 50,
 50,
 50,
 50,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 94,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 79,
 79,
 79,
 77,
 7,
 7,
 8,
 8,
 2,
 2,
 24,
 24,
 95,
 95,
 77,
 77,
 24,
 24,
 24,
 79,
 79,
 11,
 11,
 71,
 71,
 24,
 71,
 24,
 24,
 24,
 24,
 24,
 24,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 96,
 100,
 100,
 100,
 100,
 100,
 100,
 77,
 77,
 77,
 77,
 50,
 50,
 50,
 95,
 77,
 77,
 71,
 71,
 24,
 71,
 24,
 71,
 24,
 72,
 72,
 72,
 71,
 24,
 72,
 72,
 72,
 99,
 24,
 72,
 72,
 72,
 99,
 24,
 72,
 72,
 72,
 99,
 72,
 72,
 72,
 99,
 79,
 65,
 65,
 65,
 24,
 36,
 85,
 50,
 50,
 101,
 24,
 101,
 24,
 101,
 24,
 24,
 24,
 24,
 94,
 94,
 94,
 71,
 71,
 24,
 24,
 24,
 101,
 101,
 67,
 67,
 94,
 94,
 94,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 65,
 65,
 65,
 65,
 77,
 95,
 71,
 71,
 71,
 71,
 72,
 72,
 72,
 72,
 72,
 72,
 72,
 72,
 72,
 72,
 72,
 72,
 84,
 65,
 65,
 77,
 96,
 96,
 24,
 102,
 101,
 24,
 102,
 101,
 77,
 77,
 101,
 101,
 101,
 57,
 58,
 50,
 18,
 18,
 71,
 71,
 71,
 74,
 74,
 18,
 18,
 24,
 18,
 24,
 24,
 79,
 77,
 77,
 75,
 75,
 75,
 8,
 8,
 98,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 84,
 24,
 84,
 24,
 84,
 24,
 84,
 59,
 59,
 59,
 79,
 79,
 79,
 77,
 77,
 24,
 24,
 24,
 24,
 79,
 77,
 50,
 79,
 79,
 77,
 77,
 24,
 24,
 24,
 93,
 93,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 65,
 50,
 67,
 55,
 8,
 45,
 50,
 67,
 79,
 79,
 79,
 79,
 79,
 79,
 50,
 50,
 24,
 24,
 50,
 58,
 50,
 101,
 50,
 67,
 7,
 7,
 93,
 93,
 17,
 20,
 20,
 79,
 79,
 11,
 50,
 71,
 71,
 71,
 24,
 93,
 24,
 93,
 65,
 95,
 24,
 24,
 101,
 67,
 57,
 57,
 59,
 74,
 74,
 71,
 71,
 71,
 24,
 24,
 79,
 79,
 7,
 50,
 50,
 65,
 27,
 57,
 57,
 27,
 27,
 27,
 73,
 73,
 17,
 58,
 79,
 77,
 79,
 23,
 71,
 23,
 71,
 71,
 71,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 24,
 79,
 77,
 77,
 50,
 50,
 101,
 101,
 73,
 73,
 73,
 73,
 73,
 73,
 24,
 24,
 79,
 77,
 77,
 50,
 50,
 65,
 65,
 65,
 102,
 102,
 27,
 27,
 100,
 100,
 79,
 79,
 79,
 79,
 27,
 23,
 74,
 74,
 71,
 71,
 79,
 50,
 50,
 50,
 79,
 79,
 79,
 50,
 50,
 50,
 57,
 57,
 57,
 17,
 101,
 17,
 101,
 17,
 101,
 17,
 101,
 74,
 74,
 71,
 23,
 71,
 23,
 71,
 23,
 71,
 23,
 71,
 23,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 79,
 79,
 79,
 77,
 77,
 24,
 94,
 24,
 94,
 24,
 94,
 9,
 45,
 9,
 45,
 9,
 45,
 9,
 45,
 9,
 45,
 9,
 45,
 50,
 50,
 79,
 79,
 24,
 24,
 24,
 50,
 50,
 2,
 2,
 24,
 79,
 79,
 77,
 77,
 77,
 77,
 77,
 77,
 79,
 77,
 79,
 79,
 79,
 79,
 79,
 79,
 79,
 79,
 79,
 79,
 79,
 79,
 79,
 79,
 79,
 79,
 79,
 79,
 79,
 79,
 79,
 79,
 77,
 77,
 77,
 50,
 50,
 50,
 65,
 65,
 65,
 65,
 65,
 65,
 79,
 79,
 79,
 79,
 77,
 24,
 79,
 77,
 24,
 77,
 24,
 24,
 74,
 74,
 74,
 74,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 24,
 65,
 101,
 98,
 101,
 98,
 101,
 98,
 ...]

In [9]:
value = []

In [10]:
for i in jst:
  value.append(ist[i])

In [12]:
df.head()

     filename  class_number sign_class
0  000000.png            24        2.1
1  000001.png            24        2.1
2  000002.png            24        2.1
3  000003.png            24        2.1
4  000004.png            18       1.23

In [13]:
df.to_csv('table.csv')

In [22]:
import os
from PIL import Image

In [34]:
for i in range(70687):
    name = df.iloc[i]['filename']
    sign_class = df.iloc[i]['sign_class']
    
    try:
        image = Image.open(f"rtsd-public/classification/rtsd-r1/train/{name}")
        os.mkdir(f'./rtsd-public/classification/rtsd-r3/train_c/{sign_class}')
        image.save(f'rtsd-public/classification/rtsd-r3/train_c/{sign_class}/{name}')
    except:
        try:
            image.save(f'rtsd-public/classification/rtsd-r3/train_c/{sign_class}/{name}')
        except:
            pass